name: Lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        name: xmtp-keystore
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --manifest-path crates/xmtp-keystore/Cargo.toml
      - uses: actions-rs/clippy-check@v1
        name: corecrypto
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --manifest-path crates/corecrypto/Cargo.toml
